// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44394/' | (string & {});
};

export type GetPingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/arjovisualeditor/api/v1/ping';
};

export type GetPingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetPingResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetPingResponse = GetPingResponses[keyof GetPingResponses];
