// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44394/' | (string & {});
};

export type JsonElement = unknown;

export type RenderSessionRequestModel = {
    documentKey: string;
    culture: null | string;
    segment: null | string;
    values: Array<RenderValueModel>;
    variants?: null | Array<RenderVariantModel>;
};

export type RenderSessionResponseModel = {
    token: string;
    url: string;
};

export type RenderValueModel = {
    alias: string;
    culture: null | string;
    segment: null | string;
    value: JsonElement;
};

export type RenderVariantModel = {
    culture: null | string;
    segment: null | string;
    name: string;
};

export type GetPingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/arjovisualeditor/api/v1/ping';
};

export type GetPingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetPingResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetPingResponse = GetPingResponses[keyof GetPingResponses];

export type PostRenderSessionData = {
    body: RenderSessionRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/arjovisualeditor/api/v1/render-session';
};

export type PostRenderSessionErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostRenderSessionResponses = {
    /**
     * OK
     */
    200: RenderSessionResponseModel;
};

export type PostRenderSessionResponse = PostRenderSessionResponses[keyof PostRenderSessionResponses];
